Module4 task1
htmlacademy-ecmascript/942149-taskmanager-12 pull request #4
Opened 2020-08-16 16:47 UTC by Kartaviy-arteom

2020-08-20 20:22 UTC, Epsilonnnn requested changes

2020-08-20 20:22 UTC, Epsilonnnn commented on src/view/board-container.js
> +const createBoardContainerHtml = () => {
это по желанию, но можно было бы эти ф-ции во всех модулях подобных удалить и просто поместить этот код в `_getTemplate`

2020-08-20 20:22 UTC, Epsilonnnn commented on src/view/board-container.js
> +export default class BoardContainer {
Если посмотреть на все эти классы, которые рендерят элементы, то можно увидеть, что у них у всех общий интерфейс, у каждого такого класса есть:
- конструктор, в котором `this._element` всегда присваивается `null`
- методы `getTemplate`, `_getElement` (у которого в каждом классе один и тот же код), `removeElement`

Чтобы уменьшить дублирование кода между классами, в данном случае, мы можем сделать наследование, а именно завести класс `BaseComponent`, в котором будет весь общий код и от этого класса уже будут наследоваться все классы рендерящие элементы

2020-08-20 20:22 UTC, Epsilonnnn commented on src/utils.js
> +export const RenderPosition = {
это лучше вынести в consts.js

2020-08-20 20:22 UTC, Epsilonnnn commented on src/main.js
> +const renderCardBoard = (wrapper, cardsData) => {
а для чего эта ф-ция? она вроде нигде не переиспользуется

2020-08-20 20:22 UTC, Epsilonnnn commented on src/main.js
> +  cardComponent.getElement().querySelector(`.card__btn--edit`).addEventListener(`click`, () => {
там где не нужна шаблонизация лучше использовать простые кавычки

2020-08-21 08:06 UTC, Kartaviy-arteom commented on src/view/board-container.js
> +export default class BoardContainer {
Наследование будет выполнятся в пятом модуле, здесь оно пока не входит в задания. Пятый модуль целиком этому посвещен.

2020-08-21 08:09 UTC, Kartaviy-arteom commented on src/main.js
> +  cardComponent.getElement().querySelector(`.card__btn--edit`).addEventListener(`click`, () => {
Я бы с радостью, но тут так линтер настроен. Все кавычки бэктиками.

2020-08-27 16:17 UTC, Epsilonnnn approved these changes

2020-08-27 16:17 UTC, Epsilonnnn commented on src/consts.js
> +export const RenderPosition = {
именование констант в разном стиле

2020-08-27 16:36 UTC, merged